services:
  - type: cron
    name: glide-sheet-sync
    env: python
    schedule: "0 */6 * * *"  # Every 6 hours - adjust as needed
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_SHEET_ID
        value: 1F_M8Ap1ld1yNiIIM9FZaOfmiPRxl0hVw4tO9Fu8Bwzc
      # Note: GOOGLE_CREDENTIALS_JSON should be added manually via Render dashboard
      # due to JSON escaping complexity
      - key: GLIDE_MODE
        value: LEGACY
      - key: GLIDE_BASE_URL
        value: https://api.glideapp.io
      - key: GLIDE_TOKEN
        value: 54333200-37b8-4742-929c-156d49cd7c64
      - key: GLIDE_APP_ID
        value: rIdnwOvTnxdsQUtlXKUB
      - key: GLIDE_TABLE_NAME
        value: native-table-0GrR50EycwTGYCIFfPMT
      - key: UNIQUE_KEY
        value: $rowID
      - key: SHEET_NAME
        value: GlideMirror
      - key: META_SHEET
        value: _meta
      - key: WRITE_MODE
        value: delta
      - key: DERIVED_ID_HEADER
        value: ID
      - key: SELECT_COLUMNS
        value: '{"$rowID": "RowID(Glide)", "5DWpY": "Project name", "Name": "Part number", "Mzfxa": "Part name", "04Pg2": "Date created at", "yfaWu": "Assembly drawing", "Jgyps": "Status_assembly", "HqYCY": "Internal POC", "PHOD2": "Vendor POC", "QNggY": "Dispatch date"}'
      - key: LOG_ENABLED
        value: "true"
      - key: LOG_SHEET_ID
        value: 1By3o_qZ5HLXk2DYr0xVhoJw5clXRO98j0b3h0ey7JaE
      - key: LOG_DETAILS_TAB
        value: change_details
      - key: LOG_SUMMARY_TAB
        value: run_summary
